// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop_PV016.Data;

namespace Shop_PV016.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop_PV016.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Processor",
                            ShowOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Motherboard",
                            ShowOrder = 1
                        });
                });

            modelBuilder.Entity("Shop_PV016.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "The world's best desktop processor delivers superior gaming performance.",
                            Name = "AMD Ryzen 7 5700G",
                            Price = 700.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "New AMD Zen Architecture Uses Powerful Execution Engine and Supports Simultaneous Multithreading (SMT)",
                            Name = "AMD Ryzen 5 1600",
                            Price = 250.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Unlocked 12th Gen Intel Core desktop processor optimized for enthusiast gamers and serious creators",
                            Name = "Intel Core i9-12900K",
                            Price = 900.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "ASUS Prime series motherboards offer a reinforced power system, the ability to organize full-fledged component cooling, and intelligent configuration tools.",
                            Name = "Asus Prime B550M-K",
                            Price = 190.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "The Prime X570 series is made for serious people who prefer to use their Ryzen processors for more productive work.",
                            Name = "ASUS PRIME X570-P",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Z690 AORUS ELITE motherboard adopts 16+1+2 phase digital processor power supply scheme",
                            Name = "Gigabyte Z690 Aorus Elite",
                            Price = 350.0
                        });
                });

            modelBuilder.Entity("Shop_PV016.Models.Product", b =>
                {
                    b.HasOne("Shop_PV016.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
